Garage3.Web/Models/ViewModels/DetailViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Garage3.Web.Models.ViewModels
{
    public class DetailViewModel
    {
        public int Id { get; set; }

        public string Owner { get; set; } = string.Empty; //Member FullName

        public int OwnerId { get; set; }


        [Display(Name = "Type")]
        public string VehicleType { get; set; } = string.Empty;

        [Display(Name = "Registration number")]
        public string RegistrationNumber { get; set; } = string.Empty;

        [Display(Name = "Parking time")]
        public DateTime ParkingDate { get; set; }

        [Display(Name = "Time Parked")]
        public string TimeParked { get; set; } = string.Empty;

        public string Color { get; set; } = string.Empty;

        public string Brand { get; set; } = string.Empty;

        public string Model { get; set; } = string.Empty;

        [Display(Name = "Number of wheels")]
        public int NumberOfWheels { get; set; }

        public IEnumerable<int> Spots { get; set; } = new List<int>();


    }
}

Garage3.Web/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3.Core.Entities;
using Garage3.Persistence.Data;
using Garage3.Web.Models.ViewModels;
using System.Text.RegularExpressions;
using AutoMapper.Execution;
using EntityMember = Garage3.Core.Entities.Member;

namespace Garage3.Web.Controllers
{
    public class MembersController : Controller
    {
        private readonly GarageContext _context;

        public MembersController(GarageContext context)
        {
            _context = context;
        }

        // GET: Members
        public async Task<IActionResult> Index(OverviewMemberViewModel member)
        {
            IQueryable<MemberIndexViewModel> members = _context.Member.Include(m => m.Vehicles).Select(m => new MemberIndexViewModel
            {
                Id = m.Id,
                Personnummer = m.Personnummer,
                FirstName = m.FirstName,
                LastName = m.LastName,
                FullName = m.FullName,
                BirthDate = m.BirthDate,
                Membership = m.Membership,
                VehicleCount = m.Vehicles!.Count()
            }).AsQueryable();

            members = Search(member, members);
            members = Sort(member, members);

            member.Members = await members.ToListAsync();
            return View(member);
        }

        private IQueryable<MemberIndexViewModel> Search(OverviewMemberViewModel member, IQueryable<MemberIndexViewModel> members)
        {
            if (!string.IsNullOrWhiteSpace(member.By) && !string.IsNullOrWhiteSpace(member.Search))
            {
                if (member.By == nameof(member.FirstName))
                {
                    members = members.Where(m => m.FirstName.StartsWith(member.Search));
                }
                else if (member.By == nameof(member.LastName))
                {
                    members = members.Where(m => m.LastName.StartsWith(member.Search));
                }
            }

            if (member.Membership.HasValue)
            {
                members = members.Where(m => m.Membership == member.Membership);
            }

            return members;
        }

        private IQueryable<MemberIndexViewModel> Sort(OverviewMemberViewModel member, IQueryable<MemberIndexViewModel> members)
        {
            //Here we make the SortOrder param value available in the view so it can be added when submiting or click an <a> tag
            OverviewMemberViewModel.SortParam sortParams = OverviewMemberViewModel.SortParams;

            ViewData[sortParams.Personnummer] = sortParams.Personnummer;
            ViewData[sortParams.FirstName] = sortParams.FirstName;
            ViewData[sortParams.LastName] = sortParams.LastName;
            ViewData[sortParams.Membership] = sortParams.Membership;
            ViewData[sortParams.BirthDate] = sortParams.BirthDate;
            ViewData[sortParams.VehicleCount] = sortParams.VehicleCount;

            if (string.IsNullOrWhiteSpace(member.Sort))
            {
                return members;
            }

            switch (member.Sort)
            {
                case string s when s.StartsWith(sortParams.Personnummer):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.Personnummer] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.Personnummer);
                    }
                    return members.OrderByDescending(m => m.Personnummer);
                case string s when s.StartsWith(sortParams.FirstName):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.FirstName] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.FirstName.Length > 1 ? m.FirstName.Substring(0,2) : m.FirstName);
                    }
                    return members.OrderByDescending(m => m.FirstName.Length > 1 ? m.FirstName.Substring(0, 2) : m.FirstName);
                case string s when s.StartsWith(sortParams.LastName):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.LastName] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.LastName);
                    }
                    return members.OrderByDescending(m => m.LastName);
                case string s when s.StartsWith(sortParams.Membership):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.Membership] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.Membership);
                    }
                    return members.OrderByDescending(m => m.Membership);
                case string s when s.StartsWith(sortParams.BirthDate):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.BirthDate] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.BirthDate);
                    }
                    return members.OrderByDescending(m => m.BirthDate);
                case string s when s.StartsWith(sortParams.VehicleCount):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.VehicleCount] += sortParams.DescendingSuffix;//Adding descending suffix
                        return members.OrderBy(m => m.VehicleCount);
                    }
                    return members.OrderByDescending(m => m.VehicleCount);
                default:
                    return members;
            }
        }

        public bool IsValidPersonnummer(long personnummer)
        {
            const int validLength = 12;
            var personNumberString = personnummer.ToString();

            if(personNumberString.Length!=validLength)
            {
                return false;
            }

            string pattern = @"^\d{8}\d{4}$";
            Regex regex= new Regex(pattern);

            return regex.IsMatch(personNumberString);
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member.Include(m => m.Vehicles).ThenInclude(v => v.VehicleType).FirstOrDefaultAsync(m => m.Id == id);

            if (member == null)
            {
                return NotFound();
            }

            var model = new DetailsMemberViewModel
            {
                Personnummer = member.Personnummer,
                FirstName = member.FirstName,
                LastName = member.LastName,
                Membership = member.Membership,
                BirthDate = member.BirthDate,
                Id = member.Id
            };

            model.Vehicles = member.Vehicles is null ? new List<OverviewVehicleItemListViewModel>() 
                : member.Vehicles.Select(v => new OverviewVehicleItemListViewModel
            {
                Type = v.VehicleType.Name,
                RegistrationNumber = v.RegistrationNumber,
                ParkTime = v.ParkingDate,
                ParkVehicleId = v.Id


            }).ToList();
                

            return View(model);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddMemberViewModel viewModel)
        {
            try
            {
                // Validate social security number format
                if (!IsValidPersonnummer(viewModel.Personnummer))
                {
                    ModelState.AddModelError("personnummer", "Invalid Personnummer format.");
                }


                // Validate age for parking
                if (viewModel.Age < 18)
                {
                    ModelState.AddModelError("Age", "Members must be over 18 years old.");
                }
                if (ModelState.IsValid)
                {
                    var member = new EntityMember
                    {
                        Personnummer = viewModel.Personnummer,
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        //Age = viewModel.Age,
                        // Membership= viewModel.Membership
                    };

                    _context.Add(member);
                    await _context.SaveChangesAsync();
                    string informationToUser = $"Member <strong>{member.Personnummer}</strong> has been registered";
                    TempData["feedback"] = informationToUser;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException ex)
            {
                // Log the error
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }

            return View(viewModel);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

Garage3.Web/Controllers/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3.Core.Entities;
using Garage3.Persistence.Data;
using AutoMapper.Execution;

namespace Garage3.Web.Controllers
{
    public class VehicleTypesController : Controller
    {
        private readonly GarageContext _context;

        public VehicleTypesController(GarageContext context)
        {
            _context = context;
        }

        // GET: VehicleTypes
        public async Task<IActionResult> Index()
        {
              return _context.VehicleTypes != null ? 
                          View(await _context.VehicleTypes.ToListAsync()) :
                          Problem("Entity set 'GarageContext.VehicleTypes'  is null.");
        }

        // GET: VehicleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VehicleTypes == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Spaces,Name")] VehicleType vehicleType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicleType);
                await _context.SaveChangesAsync();
                string informationToUser = $"Vehicle type <strong>{vehicleType.Name}</strong> has been added";
                TempData["feedback"] = informationToUser;
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VehicleTypes == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes.FindAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Spaces,Name")] VehicleType VehicleType)
        {



            if (id != VehicleType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingVehicleType = await _context.VehicleTypes.AsNoTracking().FirstOrDefaultAsync(vt => vt.Id == VehicleType.Id);
                

                    _context.Update(VehicleType);
                    await _context.SaveChangesAsync();

                    // Checking for changes
                    List<string> changedProperties = new List<string>();

                    if (existingVehicleType.Spaces != VehicleType.Spaces)
                    {
                        changedProperties.Add("<strong>Spaces</strong>");
                    }
                    if (existingVehicleType.Name != VehicleType.Name)
                    {
                        changedProperties.Add("<strong>Name</strong>");
                    }
              
                    if (changedProperties.Count > 0)
                    {
                        string propertiesWithAChange = string.Join(" and ", changedProperties);
                        string informationToUser = $"The {propertiesWithAChange} for vehicle type with Name <strong>{VehicleType.Name}</strong> has been updated";
                        TempData["feedback"] = informationToUser;
                    }
                    else
                    {
                        TempData["feedback"] = $"No changes to type with Name {VehicleType.Name} performed";
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleTypeExists(VehicleType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(VehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VehicleTypes == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VehicleTypes == null)
            {
                return Problem("Entity set 'GarageContext.VehicleTypes'  is null.");
            }
            var vehicleType = await _context.VehicleTypes.FindAsync(id);
            if (vehicleType != null)
            {
                _context.VehicleTypes.Remove(vehicleType);
            }
            
            await _context.SaveChangesAsync();
            string informationToUser = $"<strong>{vehicleType.Name}</strong> has been deleted";
            TempData["feedback"] = informationToUser;
            return RedirectToAction(nameof(Index));
        }

        private bool ParkVehicleExists(int id)
        {
            return _context.ParkVehicle.Any(e => e.Id == id);
        }

        private bool VehicleTypeExists(int id)
        {
          return (_context.VehicleTypes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Garage3.Web/Views/Shared/_Details.cshtml
@model  Garage3.Web.Models.ViewModels.DetailViewModel

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            <a class="text-black details-link" asp-controller="Members" asp-action="Details" asp-route-Id="@Model.OwnerId">@Html.DisplayFor(modelItem => Model.Owner)</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParkingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParkingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>
    </dl>
</div>

Garage3.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garage 3.0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Exercise_12_Garage_2._0___part_1_Group1.styles.css" asp-append-version="true" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-light border-bottom box-shadow mb-3">
        <div class="container-fluid">
                <img src="~/garage30.png" alt="Garage 3.0 Logo" height="80" style="margin-bottom: 5px;" asp-area="" asp-controller="ParkVehicles" asp-action="Index" />
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Index" style="font-size: larger;">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="nav-dropdown" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: larger;">
                            Members
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Members" asp-action="Index">Overview</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Members" asp-action="Create">Add</a></li>
                        </ul>
                    </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="nav-dropdown" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: larger;">
                                Vehicles type
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="VehicleTypes" asp-action="Index">List</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="VehicleTypes" asp-action="Create">Add</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Park" style="font-size: larger;">Park</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Statistics" style="font-size: larger;">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="ParkingLotOverview" style="font-size: larger;">Parking Lot</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="main" class="container">
        <main role="main" class="pb-3">
            <p style="color:blue">@Html.Raw(TempData["feedback"])</p> @* informationToUser from ParkVehicleController goes here *@
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Group 1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>