Garage3.Web/Models/ViewModels/DetailViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Garage3.Web.Models.ViewModels
{
    public class DetailViewModel
    {
        public int Id { get; set; }

        public string Owner { get; set; } = string.Empty; //Member FullName

        public int OwnerId { get; set; }


        [Display(Name = "Type")]
        public string VehicleType { get; set; } = string.Empty;

        [Display(Name = "Registration number")]
        public string RegistrationNumber { get; set; } = string.Empty;

        [Display(Name = "Parking time")]
        public DateTime ParkingDate { get; set; }

        [Display(Name = "Time Parked")]
        public string TimeParked { get; set; } = string.Empty;

        public string Color { get; set; } = string.Empty;

        public string Brand { get; set; } = string.Empty;

        public string Model { get; set; } = string.Empty;

        [Display(Name = "Number of wheels")]
        public int NumberOfWheels { get; set; }

        public IEnumerable<int> Spots { get; set; } = new List<int>();


    }
}

Garage3.Web/Controllers/ParkVehiclesController.cs
using Garage3.Core.Entities;
using Garage3.Persistence.Data;
using Garage3.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Garage3.Web.Controllers
{
    public class ParkVehiclesController : Controller
    {
        private readonly GarageContext _context;

        public ParkVehiclesController(GarageContext context)
        {
            _context = context;
        }

        // GET: ParkVehicles
        public async Task<IActionResult> Index(OverviewVehicleViewModel searchview)
        {

            searchview.VehicleTypes = await GetVehicleTypes();

            var vehicles = _context.ParkVehicle.Include(v => v.Owner).Include(v => v.VehicleType).AsQueryable();

            vehicles = Search(searchview, vehicles);
            vehicles = Sort(searchview, vehicles);

            searchview.Vehicles = await vehicles.Select(v => new OverviewVehicleItemListViewModel
            {
                Owner = v.Owner.FullName,
                OwnerId = v.Owner.Id,
                Membership = v.Owner.Membership.ToString(),
                ParkTime = v.ParkingDate,
                ParkVehicleId = v.Id,
                RegistrationNumber = v.RegistrationNumber,
                Type = v.VehicleType.Name
            }).ToListAsync();


            return View(searchview);
        }

        public async Task<IEnumerable<SelectListItem>> GetVehicleTypes()
        {
            return await _context.VehicleTypes.Select(v => new SelectListItem(v.Name, v.Id.ToString())).ToArrayAsync();

        }

        private IQueryable<ParkVehicle> Search(OverviewVehicleViewModel vehicle, IQueryable<ParkVehicle> vehicles)
        {
            if (!string.IsNullOrWhiteSpace(vehicle.By) && !string.IsNullOrWhiteSpace(vehicle.Search))
            {
                if (vehicle.By == nameof(vehicle.RegistrationNumber))
                {
                    vehicles = vehicles.Where(v => v.RegistrationNumber.StartsWith(vehicle.Search));
                }
                else if (vehicle.By == nameof(vehicle.Owner))
                {
                    vehicles = vehicles.Where(v => v.Owner.FirstName.StartsWith(vehicle.Search));
                }
            }

            if (vehicle.Type != 0)
            {
                vehicles = vehicles.Where(v => v.VehicleTypeId == vehicle.Type);
            }

            return vehicles;
        }

        private IQueryable<ParkVehicle> Sort(OverviewVehicleViewModel vehicle, IQueryable<ParkVehicle> vehicles)
        {
            //Parameter Values for Sorting. 
            OverviewVehicleViewModel.SortParam sortParams = OverviewVehicleViewModel.SortParams;

            ViewData[sortParams.Owner] = sortParams.Owner;
            ViewData[sortParams.Membership] = sortParams.Membership;
            ViewData[sortParams.Type] = sortParams.Type;
            ViewData[sortParams.RegistrationNumber] = sortParams.RegistrationNumber;
            ViewData[sortParams.ParkTime] = sortParams.ParkTime;

            if (string.IsNullOrWhiteSpace(vehicle.Sort))
            {
                return vehicles;
            }

            switch (vehicle.Sort)
            {
                case string s when s.StartsWith(sortParams.Owner):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.Owner] += sortParams.DescendingSuffix;//Adding descending suffix
                        return vehicles.OrderBy(v => v.Owner.FirstName);
                    }
                    return vehicles.OrderByDescending(v => v.Owner.FirstName);
                case string s when s.StartsWith(sortParams.Membership):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.Membership] += sortParams.DescendingSuffix;//Adding descending suffix
                        return vehicles.OrderBy(v => v.Owner.Membership);
                    }
                    return vehicles.OrderByDescending(v => v.Owner.Membership);
                case string s when s.StartsWith(sortParams.Type):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.Type] += sortParams.DescendingSuffix;//Adding descending suffix
                        return vehicles.OrderBy(v => v.VehicleType.Name);
                    }
                    return vehicles.OrderByDescending(v => v.VehicleType.Name);
                case string s when s.StartsWith(sortParams.RegistrationNumber):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.RegistrationNumber] += sortParams.DescendingSuffix;//Adding descending suffix
                        return vehicles.OrderBy(v => v.RegistrationNumber);
                    }
                    return vehicles.OrderByDescending(v => v.RegistrationNumber);
                case string s when s.StartsWith(sortParams.ParkTime):
                    if (!s.EndsWith(sortParams.DescendingSuffix))
                    {
                        ViewData[sortParams.ParkTime] += sortParams.DescendingSuffix;//Adding descending suffix
                        return vehicles.OrderBy(v => v.ParkingDate);
                    }
                    return vehicles.OrderByDescending(v => v.ParkingDate);
                default:
                    return vehicles;
            }

        }

        [AcceptVerbs("GET", "POST")]
        //this method is defined under [Remote] data annotation to check uniqueness
        public async Task<IActionResult> IsRegistrationNumberExists(string registrationNumber, string existingRegistrationNumber)
        {
            if (registrationNumber == existingRegistrationNumber)
            {
                return Json(true);
            }
            bool isRegistrationNumberExists = false;
            try
            {
                //checks if the existing reg num equals with the entered reg num
                isRegistrationNumberExists = await _context.ParkVehicle.AnyAsync(v => v.RegistrationNumber.Equals(registrationNumber));
                return Json(!isRegistrationNumberExists);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        // GET: ParkVehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ParkVehicle == null)
            {
                return NotFound();
            }
            //creating instance for model and assigning values to the model
            var detailsViewModel = await _context.ParkVehicle.Include(v => v.VehicleType)
                .Select(v => new Garage3.Web.Models.ViewModels.DetailViewModel
                {
                    Id = v.Id,
                    RegistrationNumber = v.RegistrationNumber,
                    Brand = v.Brand,
                    Color = v.Color,
                    Model = v.Model,
                    NumberOfWheels = v.NumberOfWheels,
                    ParkingDate = v.ParkingDate,
                    VehicleType = v.VehicleType.Name,
                    Owner = v.Owner.FullName,
                    OwnerId = v.Owner.Id
                })
                .FirstOrDefaultAsync(m => m.Id == id);

            if (detailsViewModel == null)
            {
                return NotFound();
            }

            return View(detailsViewModel);
        }



        // GET: ParkVehicles/Park
        public async Task<IActionResult> Park()
        {
            var model = new ParkVehicleViewModel();
            model.VehicleTypes = await GetParkVehicleTypes();

            ViewBag.MembershipType = new SelectList(Enum.GetValues(typeof(Membership)));


            return View(model);
        }

        // POST: ParkVehicles/Park
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Park([Bind("Personnummer, MembershipType, RegistrationNumber, VehicleTypeId, Color, Brand, Model, NumberOfWheels")] ParkVehicleViewModel parkVehicleViewModel)
        {
            var member = await _context.Member
                .SingleOrDefaultAsync(m => m.Personnummer == parkVehicleViewModel.Personnummer);

            if (member == null)
            {
                ModelState.AddModelError("Personnummer", "Member does not exist");
            }
            if (ModelState.IsValid)
            {
                if (await _context.ParkVehicle.AnyAsync(v => v.RegistrationNumber.Equals(parkVehicleViewModel.RegistrationNumber)))
                {
                    ModelState.AddModelError("RegistrationNumber", "Registration Number already exists");
                }
                else
                {
                    var parkVehicle = new ParkVehicle
                    {
                        Owner = member,
                        RegistrationNumber = parkVehicleViewModel.RegistrationNumber,
                        VehicleTypeId = parkVehicleViewModel.VehicleTypeId,
                        Color = parkVehicleViewModel.Color,
                        Brand = parkVehicleViewModel.Brand,
                        Model = parkVehicleViewModel.Model,
                    };

                    ICollection<ParkingSpace> spots = await GetWhereToPark(parkVehicle.VehicleTypeId, s => s.VehicleId == null);

                    if (spots.Any())
                    {
                        parkVehicle.Spots = spots;
                        _context.Add(parkVehicle);
                        await _context.SaveChangesAsync();

Garage3.Web/Views/Members/Create.cshtml
@model AddMemberViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Personnummer" class="control-label"></label>
                <input asp-for="Personnummer" class="form-control" />
                <span asp-validation-for="Personnummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="Membership" class="control-label"></label>
                <select class="form-select" asp-for="Membership" asp-items="@Html.GetEnumSelectList<Membership>()">
                </select>
                <span asp-validation-for="Membership" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3.Web/Views/Members/Delete.cshtml
@model Garage3.Core.Entities.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Personnummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Personnummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Membership)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Membership)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Garage3.Web/Views/Members/Details.cshtml
@model DetailsMemberViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Personnummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Personnummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Membership)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Membership)
        </dd>
    </dl>
    
    <hr />
    <h5>Member's vehicles</h5>
    @if (Model.Vehicles.Any())
    {
        <table class="table">
            <thead>
                <tr class="table-header-with-sort">
                    <th>
                       @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RegistrationNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ParkTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TimeParked)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Vehicles)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                             <a class="text-black details-link" asp-controller="ParkVehicles" asp-action="Details" asp-route-Id="@item.ParkVehicleId" >@Html.DisplayFor(modelItem => item.RegistrationNumber)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ParkTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeParked)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="ms-3">No vehicles registered</p>
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Garage3.Web/Views/Members/Edit.cshtml
@model Garage3.Core.Entities.Member

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Personnummer" class="control-label"></label>
                <input asp-for="Personnummer" class="form-control" />
                <span asp-validation-for="Personnummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Membership" class="control-label"></label>
                <select class="form-select" asp-for="Membership" asp-items="@Html.GetEnumSelectList<Membership>()">
                </select>
                <span asp-validation-for="Membership" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3.Web/Views/Members/Index.cshtml
@model OverviewMemberViewModel

@{
    ViewData["Title"] = "Members overview";
    OverviewMemberViewModel.SortParam sortParams = OverviewMemberViewModel.SortParams;
}

<h1>Members</h1>

<form method="get">
    <div class="row mb-3">
        <div class="col-12 col-md-auto pe-md-0">
            <select class="form-select w-auto" asp-for="By">
                <option value="@nameof(Model.FirstName)" selected>First name</option>
                <option value="@nameof(Model.LastName)">Last name</option>
            </select>
        </div>
        <div class="col-md ps-md-0 pb-3 pb-md-0">
            <input type="text" class="form-control col-4" placeholder="Search First name" asp-for="Search">
        </div>
        <div class="col-auto pb-3 pb-md-0">
            <select class="form-select col-auto" asp-for="Membership" asp-items="@Html.GetEnumSelectList<Membership>()">
                <option value="" selected>Membership</option>
            </select>
        </div>
        <input type="hidden" asp-for="Sort" />
        <div class="col-12 col-md-auto">
            <button class="btn btn-primary" id="Search-Button">Search</button>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr class="table-header-with-sort">
            <th>
                <a asp-action="Index" asp-route-By="@Model.By" asp-route-Search="@Model.Search" asp-route-Type="@Model.Membership" asp-route-Sort="@ViewData[sortParams.Personnummer]">@Html.DisplayNameFor(model => model.Personnummer)<i class="@Model.GetSortSymbol(sortParams.Personnummer)"></i></a>
            </th>
            <th>
                <a asp-action="Index" asp-route-By="@Model.By" asp-route-Search="@Model.Search" asp-route-Type="@Model.Membership" asp-route-Sort="@ViewData[sortParams.FirstName]">@Html.DisplayNameFor(model => model.FirstName)<i class="@Model.GetSortSymbol(sortParams.FirstName)"></i></a>
            </th>
            <th>
                <a asp-action="Index" asp-route-By="@Model.By" asp-route-Search="@Model.Search" asp-route-Type="@Model.Membership" asp-route-Sort="@ViewData[sortParams.LastName]">@Html.DisplayNameFor(model => model.LastName)<i class="@Model.GetSortSymbol(sortParams.LastName)"></i></a>
            </th>
            <th>
                <a asp-action="Index" asp-route-By="@Model.By" asp-route-Search="@Model.Search" asp-route-Type="@Model.Membership" asp-route-Sort="@ViewData[sortParams.Membership]">@Html.DisplayNameFor(model => model.Membership)<i class="@Model.GetSortSymbol(sortParams.Membership)"></i></a>
            </th>
            <th>
                <a asp-action="Index" asp-route-By="@Model.By" asp-route-Search="@Model.Search" asp-route-Type="@Model.Membership" asp-route-Sort="@ViewData[sortParams.VehicleCount]">@Html.DisplayNameFor(model => model.VehicleCount)<i class="@Model.GetSortSymbol(sortParams.VehicleCount)"></i></a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Members)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Personnummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Membership)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleCount)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    let searchBySelect = document.querySelector('#By');
    let SearchTextInput = document.querySelector('#Search');

    searchBySelect.addEventListener("change", function (e) {
        SearchTextInput.value = "";
        SearchTextInput.placeholder = `Search ${searchBySelect.options[searchBySelect.selectedIndex].text}`;
        SearchTextInput.focus();
    });
</script>